[package]
name = "jogo_de_advinhacao"
version = "0.1.0"
edition = "2021"
authors = ["Danilo S Andrade <danilo.s.andrade@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = [] }
